name: Ansible basic

on: workflow_dispatch

jobs:
  ansible-ping:
    runs-on: ubuntu-latest
    run: ls la
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: ansible-playbook .environment/ping.yml

