name: jobs examples

on:
   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: example of invalid command
        run: ecko Hello, world! Build failed.


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do job2
        run: echo Hello, world! Job2.


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
