name: jobs examples

on:
   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artifact for reuse
        run: echo “Full featured artifact” > build-result.txt


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: use of artifact created
        run: ls build-result.txt


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
